version: "3.9"

services:
  postgres:
    image: postgres:15.1-alpine3.17
    container_name: postgres_testCurrencyBalance
    hostname: postgres_testCurrencyBalance
    env_file:
      - .env
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    restart: on-failure

  nats-streaming:
    image: nats-streaming:0.25.3-alpine3.17
    container_name: nats_testCurrencyBalance
    hostname: nats_testCurrencyBalance
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always